### ISSUE TITLE
can't use in 0.4.10

### ISSUE THREAD

**Issue by DevilPaean** [altmank/CaptainOfCheats#17] opened 2022-08-23 04:55 UTC
thank you for your convenient cheating, it's awesome.
now the game update 0.4.10 and mod can't work anymore, will you update it if you have time?

**Comment by altmank** [comment] 2022-08-23 05:05
The current release is compatible with 0.4.10. Please verify your installation or provide details about your issue loading the mod.

**Comment by DevilPaean** [comment] 2022-08-23 07:21
v1.8.0 works perfect with 0.4.9 last month.
but after update 0.4.10 today, it doesnt work...

**Comment by altmank** [comment] 2022-08-23 07:27
Hi, I have 0.4.10, running with COI 1.8.0. This is why I say they are compatible. If you are having an issue, I cannot troubleshoot without more information. Let's start with you sharing your most recent log file from \Documents\Captain of Industry\Logs.

**Comment by DevilPaean** [comment] 2022-08-23 07:28
sorry i dont know why i suddenly cant upload image or file to github and i cant even edit post....
sorry for interrupt you...

**Comment by altmank** [comment] 2022-08-23 07:29
Okay. You can also message me your log file on Discord under 'xceled'. I'll close this ticket for now until additional information is provided.

**Comment by DevilPaean** [comment] 2022-08-23 07:29
is this? sorry i cant upload a file....


I 07:15:07,040 S------ ~Mai: Started logging to file
I 07:15:07,086 S------ ~Mai: Unity logging registered
I 07:15:07,086 S------ ~Mai: Staring game (standalone) ...
I 07:15:07,102 S------ ~Mai: UTC now: 2022/08/23 07:15:07
G 07:15:07,102 S------ ~Mai: Version: 0.4.10 (Early Access)
I 07:15:07,103 S------ ~Mai: Current culture: zh-CN
I 07:15:07,104 S------ ~Mai: Platform: 2
I 07:15:07,292 S------ ~Mai: Steam client connected
I 07:15:07,318 S------ ~Mai: Default language 'English'
I 07:15:07,864 S------ ~Mai: VSync set to 1
I 07:15:07,865 S------ ~Mai: Target FPS set to -1
I 07:15:07,868 S------ ~Mai: Loaded 3 core mods:
  CoreMod (Mafi.Core.CoreMod)
  BaseMod (Mafi.Base.BaseMod)
  UnityMod (Mafi.Unity.UnityMod)
I 07:15:07,869 S------ ~Mai: Loading mods from 'C:\Games\Captain.of.Industry.v0.4.10\DLCs'.
I 07:15:07,871 S------ ~Mai: Loading mods from 'C:\Games\Captain.of.Industry.v0.4.10\DLCs\Mafi.Supporter\Mafi.Supporter.dll'.
I 07:15:07,878 S------ ~Mai: Mods type 'Mafi.Supporter.SupporterMod' registered (with asset bundles).
I 07:15:07,880 S------ ~Mai: DLC 'Mafi.Supporter' is not installed, skipping.
I 07:15:07,882 S------ ~Mai: Loading mods from 'C:\Users\DP\Documents\Captain of Industry\Mods'.
I 07:15:07,882 S------ ~Mai: Loading mods from 'C:\Users\DP\Documents\Captain of Industry\Mods\CaptainOfCheats\CaptainOfCheats.dll'.
I 07:15:07,888 S------ ~Mai: Mods type 'CaptainOfCheats.CaptainOfCheatsMod' registered (with asset bundles).
I 07:15:07,888 S------ ~Mai: Closing graylog logging.
I 07:15:07,889 S------ ~Mai: Loaded 1 extra mods
    CaptainOfCheats (CaptainOfCheats.CaptainOfCheatsMod)
I 07:15:08,963 S------ ~Mai: Game was initialized in 1 steps and took 0.630 seconds to complete.
I 07:15:08,967 S------ ~Mai: Total memory: 19 MB, GC collected 0 MB in 2.8937 ms.
I 07:15:19,922 S------ ~Mai: Configs instantiated: GameDifficultyConfig, StaticIslandMapProviderConfig, IslandMapDifficultyConfig, RandomSeedConfig, TerrainGeneratorConfig, IslandMapGeneratorConfig, CoreModConfig, MaintenanceConfig, BaseModConfig, StartingFactoryConfig, UnityModConfig
W 07:15:19,954 S------ ~Mai: Bundles manifest file is missing, bundles may be read in incorrect order causing missing assets. Expected path: C:\Users\DP\Documents\Captain of Industry\Mods\CaptainOfCheats\AssetBundles\mafi_bundles.manifest
I 07:15:21,642 S------ ~Mai: [1780 ms] Instantiated mods.
I 07:15:21,719 S------ ~Mai: Registered 164 products from assembly 'Mafi.Base'.
I 07:15:22,515 S------ ~Mai: [CaptainOfCheats]: Running version v1.8.0
I 07:15:22,515 S------ ~Mai: [858 ms] Initialized mods.
I 07:15:22,713 S------ ~Mai: Sim thread enabled: True
I 07:15:22,713 S------ ~Mai: Game ID: 237338486384835938; Session ID: 5576061079650343917
I 07:15:23,248 S------ ~Mai: [CaptainOfCheats]: Found 6 cheat tabs
I 07:15:23,250 S------ ~Mai: [733 ms] Instantiated all dependencies.
I 07:15:23,254 S000000 ~Mai: [2.46 ms] NewGameCreated: UnlockedProtosDb
I 07:15:23,271 S000000 ~Mai: [3.29 ms] NewGameCreated: PopsHealthManager
I 07:15:23,286 S000000 ~Mai: [1.44 ms] NewGameCreated: TerrainManager
I 07:15:48,276 S000000 ~Mai: [25000 ms] Terrain generated
I 07:15:48,277 S000000 ~Mai: [0.00910 ms] NewGameCreated: SimulationBackgroundTask
I 07:15:48,294 S000001 ~Mai: [0.711 ms] NewGameCreated: WorldMapManager
I 07:15:48,311 S000001 ~Mai: [1.05 ms] Generating new world map.
I 07:15:48,393 S000001 ~Mai: [65.3 ms] World map generated.
I 07:15:48,393 S000001 ~Mai: [0.00710 ms] NewGameCreated: OceanTerrainManager
I 07:15:50,739 S000001 ~Mai: [2330 ms] Ocean expanded.
I 07:15:50,740 S000001 ~Mai: [0.0102 ms] NewGameCreated: VirtualResourceManager
I 07:15:50,747 S000001 ~Mai: [3.71 ms] NewGameCreated: EdictsManager
I 07:15:50,765 S000001 ~Mai: [4.59 ms] NewGameCreated: MessagesManager
I 07:15:50,782 S000001 ~Mai: [4.72 ms] NewGameCreated: StartingFactoryBuilder
I 07:15:51,038 S000002 ~Mai: [244 ms] Performing init sim updates: 0, still waiting on: 
I 07:15:51,040 S000002 ~Mai: [0.467 ms] NewGameInitialized: Calendar
I 07:15:51,044 S000002 ~Mai: [0.548 ms] RendererInitState: GameConsoleCommandsExecutor
I 07:15:51,091 S000002 ~Mai: Registered 27 console commands.
I 07:15:51,091 S000002 ~Mai: [31.0 ms] RendererInitState: CameraController
I 07:15:51,093 S000002 ~Mai: [0.814 ms] RendererInitState: WaterRenderer
I 07:15:51,615 S000002 ~Mai: [504 ms] RendererInitState: WeatherController
I 07:15:51,618 S000002 ~Mai: [1.94 ms] RendererInitState: TreeRenderer
I 07:15:51,786 S000002 ~Mai: [159 ms] RendererInitState: TerrainRenderer
I 07:15:56,246 S000002 ~Mai: [4450 ms] RendererInitState: IoPortsRenderer
I 07:15:56,255 S000002 ~Mai: [6.89 ms] RendererInitState: ConstructionCubesUpdater
I 07:15:56,263 S000002 ~Mai: [0.677 ms] RendererInitState: EntitiesRenderer
I 07:15:56,336 S000002 ~Mai: [57.5 ms] RendererInitState: TransportedProductsRenderer
I 07:15:56,342 S000002 ~Mai: [1.62 ms] RendererInitState: TransportPillarsRenderer
I 07:15:56,363 S000002 ~Mai: [1.31 ms] RendererInitState: TerrainDesignationsRenderer
I 07:15:56,379 S000002 ~Mai: [0.220 ms] RendererInitState: MineTowerAreasRenderer
I 07:15:56,397 S000002 ~Mai: [1.39 ms] RendererInitState: GameUiInstantiator
I 07:15:56,420 S000002 ~Mai: [7.84 ms] Resolved 102 UI classes.
I 07:15:56,430 S000002 ~Mai: [0.787 ms] Building UI: 1 / 10
I 07:15:56,620 S000002 ~Mai: [174 ms] Building UI: 2 / 10
I 07:15:56,694 S000002 ~Mai: [69.0 ms] Building UI: 3 / 10
I 07:15:57,509 S000002 ~Mai: [812 ms] Building UI: 4 / 10
I 07:15:57,679 S000002 ~Mai: [166 ms] Building UI: 5 / 10
I 07:15:58,004 S000002 ~Mai: [320 ms] Building UI: 6 / 10
I 07:15:58,544 S000002 ~Mai: [536 ms] Building UI: 7 / 10
I 07:15:59,017 S000002 ~Mai: [468 ms] Building UI: 8 / 10
I 07:15:59,604 S000002 ~Mai: [582 ms] Building UI: 9 / 10
I 07:16:01,740 S000002 ~Mai: [2130 ms] Building UI: 10 / 10
I 07:16:01,751 S000002 ~Mai: [CaptainOfCheats]: Started building cheat menu
I 07:16:01,752 S000002 ~Mai: [CaptainOfCheats]: Adding General tab to cheat menu
I 07:16:01,766 S000002 ~Mai: [CaptainOfCheats]: Adding Generate tab to cheat menu
I 07:16:01,781 S000002 ~Mai: [CaptainOfCheats]: Adding Shipyard tab to cheat menu
I 07:16:01,794 S000002 ~Mai: [CaptainOfCheats]: Adding Terrain tab to cheat menu
I 07:16:01,807 S000002 ~Mai: [CaptainOfCheats]: Adding Vehicles tab to cheat menu
I 07:16:01,818 S000002 ~Mai: [CaptainOfCheats]: Adding Weather tab to cheat menu
I 07:16:01,826 S000002 ~Mai: [CaptainOfCheats]: Finished building cheat menu
X 07:16:01,827 S000002 ~Mai: Exception during game initialization.
 ---> MissingMethodException: Method not found: Mafi.Unity.UiFramework.Components.ToggleBtn Mafi.Unity.UiFramework.Components.ToggleBtn.AddTooltip(Mafi.Localization.LocStrFormatted)
  at Mafi.Unity.UserInterface.GameUiInstantiator+<buildUi>d__1.MoveNext () [0x000ed]  
  at Mafi.Core.GameLoop.GameLoopEvents+<InvokeRendererInitializeState>d__51.MoveNext () [0x000d3]  
  at Mafi.Core.GameLoop.GameRunner+<Initialize>d__93.MoveNext () [0x002dc]  
  at Mafi.Core.Game.GameBuilder+<initializeGame>d__4.MoveNext ()  
  at Mafi.Core.Game.GameBuilder+<BuildNewGameTimeSliced>d__1.MoveNext ()  
  at Mafi.Unity.GamePlayScene+<buildNewGame>d__13.MoveNext () [0x0007a]  
  at Mafi.Unity.GamePlayScene+<Initialize>d__12.MoveNext () [0x000a5]  
  at Mafi.Unity.Main.Update ()  
I 07:16:02,214 S000002 ~Mai: Game was initialized in 1 steps and took 0.345 seconds to complete.
I 07:16:02,279 S000002 ~Mai: Total memory: 849 MB, GC collected 2 MB in 64.555 ms.
I 07:17:03,939 S000002 ~Mai: Requesting game quit.
I 07:17:03,960 S000002 ~Mai: Closing file logging

**Comment by DevilPaean** [comment] 2022-08-23 07:33
really sorry.... actually i thought i upload an image in 2nd post but it seems that my internet have some problem...

**Comment by altmank** [comment] 2022-08-23 07:40
Interesting error you are getting:
---> MissingMethodException: Method not found: Mafi.Unity.UiFramework.Components.ToggleBtn Mafi.Unity.UiFramework.Components.ToggleBtn.AddTooltip(Mafi.Localization.LocStrFormatted)

It is saying that a UI button function isn't available. This is built into the game code. I can't reproduce the issue on my side (code still exists in the game code) and you're the only reporter so far.

Can you confirm you are on the stable branch of the game? If so, can you also try doing an integrity check of the game files from steam?
https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

**Comment by DevilPaean** [comment] 2022-08-23 07:45
it works....my fucking internet....
really sorry for wasting your time....

**Comment by altmank** [comment] 2022-08-23 07:46
Glad it worked out in the end. Take care.

**Closed by altmank** 2022-08-23 07:46 UTC
