### ISSUE TITLE
Waste Processing plant has no outputs.

### ISSUE THREAD

**Issue by Meerletalis** [altmank/CaptainOfCheats#7] opened 2022-06-27 01:47 UTC
Starting with your mod as I have seen no reports of this in base game.  Nothing in the captain of Industry log.  Trucks nor storages seem to get scrap, but the recyclables still process
[Newton.zip](https://github.com/altmank/CaptainOfCheats/files/8988078/Newton.zip)
.

**Comment by altmank** [comment] 2022-06-28 23:27
@Meerletalis So I can reproduce in a new save, and in your save, but my existing save which I've been playing for a few versions with COC installed, doesn't have the issue. Nothing is logged by regarding it as far as I can tell. I'm unsure if the issue exists in the base game under certain conditions as well as that would be time consuming to test.

Do you have any background about what cheats you've used in your save that has the issue? I've asked the devs about it as I'm not really touching any of the code around recylcing, so I don't see any obvious suspects on my side.

**Comment by Meerletalis** [comment] 2022-06-29 02:47
I will try it again in another save at some point.  I was using your mod to experiment with island growing.  I added a bunch of trucks, set up some endless supplies (Not recyclables on purpose), added a bunch of material to the shipyard.  (only COC if that was the question)

**Comment by altmank** [comment] 2022-06-29 03:26
@Meerletalis I'm going to close this issue as won't fix unfortunately. It looks like this is just an inherent design choice by the developers regarding how god-mode/recycling tracking works. This is my evaluation after looking at some of the built in game code around how recycling tracking works. My code does not own either function so they are out of scope for me to fix. COC only hooks into the existing god-mode provided by the developers.

**Closed by altmank** 2022-06-29 03:26 UTC
Labels: bug
