### ISSUE TITLE
Truck Capacities Don't Reset

### ISSUE THREAD

**Issue by epoch18** [altmank/CaptainOfCheats#8] opened 2022-07-02 20:16 UTC
Using the mod, under Vehicles menu I selected the +500% Truck Capacity Multiplier. Worked fine. 

After a bit, clicked the Reset button and no change. 

Thanks.

**Comment by altmank** [comment] 2022-07-02 20:28
@epoch18 Can you provide your save file where you have a permanent +500% that you cannot reset?

**Comment by epoch18** [comment] 2022-07-02 23:25
[22-07-02_16-17-46_1048-autosave.zip](https://github.com/altmank/CaptainOfCheats/files/9033842/22-07-02_16-17-46_1048-autosave.zip)

Pickups at 120
Large Trucks at 360

**Comment by epoch18** [comment] 2022-07-04 10:59
Clicking +100 now sets (for example) trucks to 420 and +200% sets them to 480. Clicking either +500% or Reset puts it back to 360.

**Comment by altmank** [comment] 2022-07-04 15:51
Fixed in commit ac399a3f

**Closed by altmank** 2022-07-04 15:51 UTC

**Comment by altmank** [comment] 2022-10-11 09:10
Hello, I cannot reproduce. Can you please provide additional information
that may help me reproduce the issue?
