### ISSUE TITLE
Instant Dump - Overlay seems wrong 

### ISSUE THREAD

**Issue by FrankBKK** [altmank/CaptainOfCheats#35] opened 2023-06-02 09:03 UTC
Using the latest CoC version, COI 5.0b
![COI-InstantDump-Layers](https://github.com/altmank/CaptainOfCheats/assets/12725516/1a6c704b-e40f-442e-8301-336321817ede)

When instant mining an area off a small horizontal layer (e.g. from +03 to +01) and then instant dump dirt back to the original layer (+03) the overlay map seems wrong. 

see the attached pic.

**Comment by JonJoyce** [comment] 2023-06-02 13:39
+1

**Comment by altmank** [comment] 2023-06-02 14:35
Interesting, will take a look. I'm not actually controlling any code specific to the overlay but I did have to switch over to an entirely different provider for making terrain changes, so perhaps something about the way I am using it is causing this. Appreciate the details.

**Comment by JonJoyce** [comment] 2023-06-02 15:26
@altmank I did some fairly extensive flattening for my test map... its quite extreme.
![image](https://github.com/altmank/CaptainOfCheats/assets/448438/5142257f-5744-42bf-80d8-d0e90ebcbc6b)

**Comment by altmank** [comment] 2023-06-02 15:28
Okay. I would suggest keeping a backup of your save before the terrain edits. I may be able to fix the root cause but it may not fix any map edits done with the old code.

**Comment by JonJoyce** [comment] 2023-06-02 18:06
@altmank Its a weird one, only seems to happen if you dump over the top of existing materials. 
So if you cover iron ore with dirt (or change terrain) then it happens. Over ocean or standard rock it doesnt happen.

**Comment by JonJoyce** [comment] 2023-06-02 18:08
![image](https://github.com/altmank/CaptainOfCheats/assets/448438/94d430dd-b734-4b15-aa7a-669621e23760)
Here's an example on a new save. Only thing done, set dumping area, instant dump rock.

**Comment by altmank** [comment] 2023-06-02 18:09
I'm going to have to rewrite all of the terrain cheat code again I think.

**Comment by JonJoyce** [comment] 2023-06-02 18:27
Had a bit more a play, looks like when you dump it fully _pushes_ the ore all the way **way** down.
![image](https://github.com/altmank/CaptainOfCheats/assets/448438/ca5abeb7-c989-4501-850d-57ec888876af)

**Comment by altmank** [comment] 2023-06-02 18:30
You don't need to provide any additional detail, I'm good on steps to reproduce, as mentioned I have to rewrite all of the dumping and mining code.

**Comment by altmank** [comment] 2023-06-03 01:18
Fixed in v2.1.0

**Closed by altmank** 2023-06-03 01:18 UTC
